### ISSUE TITLE
Ordre des colonnes dans Statsgrid

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/html.widgets.statsgrid#2]
Je reprends un projet avec initialement commencé par l'utilisateur  qui a trouvé le bug sur les entiers.
je viens de trouver ce que je pense être une incohérence de sortie de datas ou une fois de plus une incompétence de ma part :o)
dans le cas d'un tableau en multi colonnes dont les données sont numériques  je n'arrive pas à ordonner celui-ci sur le rendu $grid->toHtml();
Il prend correctement mon tableau en entrée qui est ordonné et le ressort dans le même ordre.
Un petit exemple sera plus parlant, en entrée
type L  l  P
test 10 10 0
test 10 12 0
test 10 15 0
test 10 20 0
test 10 24 0
test 10 30 0
test 10 40 0
test 12 15 0
test 12 20 0
test 12 30 0
test 12 40 0
test 15 15 0
test 15 20 0
test 15 30 0
test 15 40 0
test 20 20 0
test 20 24 0
test 20 30 0
test 20 40 0
test 20 50 0
test 20 60 0
test 20 70 0
test 20 80 0
test 20 90 0
test 20 100 0
test 21 46 0
test 22 22 0

mon rendu de colonne me donne
10 12 15 20 24 30 40 60 70 80 90 100 46 22

le 46 et le 22 sont donc erronés et je ne vois pas après une bonne recherche le souci
dans l'attente d'une réponse de votre part je vous remercie par avance

**Comment by moufmouf** [comment]
Bonjour Franck,

Statsgrid permet d'avoir des colonnes dont le titre est une chaîne de caractères (par exemple, un nom d'entreprise ou un nom de mois).
Du coup, il ne fait pas de tri pour ordonner les colonnes dans un ordre particulier.

Par contre, vous pouvez faire ce tri vous même avant d'appeler Statsgrid.

Si tu cherches dans ton code, tu devrais voir à un endroit:

```
$grid->addColumn(...);
```

C'est la partie du code qui déclare les colonnes, une par une.
Les colonnes sont ordonnées dans l'ordre d'appel à addColumn.
Donc si tu as un appel dans ce sens:

```
    $grid->addColumn(100);
    $grid->addColumn(46);
```

Alors le 46 sera affiché après le 100.

Ce que tu peux faire, c'est simplement faire un [sort](http://php.net/manual/fr/function.sort.php) de ton array qui contient les colonnes avant d'appeler "addColumn".

Et tes colonnes devraient s'afficher sans problème.

J'espère que mes explications sont claires. Sinon, si tu as besoin d'aide, tu peux ajouter le bout de code qui génère la grid ici, je tacherais de t'aider.

**Comment by xoko** [comment]
Bonjour,
encore merci pour cette réponse.
Pour infos j'ai cherché de mon coté et je suis arrivé (ce WE ) à la modification suivante dans la class StatsColumnDescriptor:

public function getDistinctValues($dataset) {
        $values = array();
        foreach ($dataset as $row) {
            $values[$row[$this->key]] = 1;
        }

```
    ksort($values); //ajout du tri
    // Note: warning: with this method, we loose the type of the value (int or string)
    return array_keys($values);
}
```

j'ai donc ajouté un ksort sur le tableau des $dataset
cela te parait-il pertinent ?
cela semble fonctionner mais je n'ai pas tester la totalité des cas.

cordialement

**Comment by moufmouf** [comment]
Bonjour Frank,

Celà répond certainement à ton besoin, mais je ne peux pas intégrer cette ligne dans Statsgrid comme ça.
En effet, en faisant le "ksort", tu tries les noms des colonnes, ce que tu cherches.

Mais plein d'autres personnes ne souhaitent pas les trier. Par exemple, si tes colonnes sont des mois de l'année (Janvier/Février...), on ne voudra pas les trier par ordre alphabétique (ce que ferait ksort).

Je pense que j'ai besoin de réfléchir un peu plus à ce problème.... peut être rajouter un paramètre optionnel de tri.... Je vais creuser le point, maintenant que je comprend mieux ton problème.

**Comment by xoko** [comment]
Oui en effet c'est une modification à l'arrache.
Par contre je me suis posé la même question que toi, à savoir comment intégrer le trie sur les colonnes avec un système de choix. Ne maitrisant pas assez ton outil, j'ai laissé le code tel quel pour le moment afin d'éviter les bêtises. J'y reviendrai certainement plus tard je pense, car c'est une option intéressante.

cordialement

**Comment by moufmouf** [comment]
Ok, je pense avoir fait quelque chose de propre et qui répond à ton besoin.
Par défaut, je fais le sort que tu proposes (parce que c'est le comportement qu'on cherche à avoir le plus fréquemment).
J'ai quand même fait une méthode "setSort" qui permet de désactiver le sort, ou de passer une fonction de comparaison pour avoir un tri dans un ordre custom.

J'ai documenté tout ça ici: https://github.com/thecodingmachine/html.widgets.statsgrid
Merci pour le feedback!
